export enum Types {
    SET_GOOGLE_AUTH = 'SET_GOOGLE_AUTH',
    UPDATE_GOOGLE_IS_SIGNED_IN = 'UPDATE_GOOGLE_IS_SIGNED_IN',
    GOOGLE_SIGN_IN = 'GOOGLE_SIGN_IN',
    GOOGLE_SIGN_OUT = 'GOOGLE_SIGN_OUT',

    GET_CHANNEL_INFO = 'GET_CHANNEL_INFO',

    UPDATE_PLAYER_STATE = 'UPDATE_PLAYER_STATE',
    // UPDATE_PLAYER_VOLUME = 'UPDATE_PLAYER_VOLUME',
    UPDATE_PLAYER_VIDEO1_VOLUME = 'UPDATE_PLAYER_VIDEO1_VOLUME',
    UPDATE_PLAYER_VIDEO2_VOLUME = 'UPDATE_PLAYER_VIDEO2_VOLUME',
    UPDATE_PLAYER_PROGRESS = 'UPDATE_PLAYER_PROGRESS',
    UPDATE_PLAYER_CURRENT_TIME = 'UPDATE_PLAYER_CURRENT_TIME',
    UPDATE_PLAYER_ON_READY = 'UPDATE_PLAYER_ON_READY',
    UPDATE_PLAYER_MAX_VIDEO_DURATION = 'UPDATE_PLAYER_MAX_VIDEO_DURATION',
    UPDATE_PLAYER_IS_TIME_PERCENTAGE = 'UPDATE_PLAYER_IS_TIME_PERCENTAGE',
    SET_PLAYER_IS_TIME_UPDATE = 'SET_PLAYER_IS_TIME_UPDATE',
    CLEAR_PLAYER_CONTROL = 'CLEAR_PLAYER_CONTROL',

    SEARCH_VIDEOS = 'SEARCH_VIDEOS',
    ADD_VIDEO_TO_ANALYTICS = 'ADD_VIDEO_TO_ANALYTICS',
    REMOVE_VIDEO_FROM_ANALYTICS = 'REMOVE_VIDEO_FROM_ANALYTICS',
    REMOVE_ALL_VIDEO_FROM_ANALYTICS = 'REMOVE_ALL_VIDEO_FROM_ANALYTICS',
    SET_RETENTION_GRAPH = 'SET_RETENTION_GRAPH',
    REMOVE_RETENTION_GRAPH = 'REMOVE_RETENTION_GRAPH',
}

export type ActionMap<M extends { [index: string]: any }> = {
    [Key in keyof M]: M[Key] extends undefined
        ? {
              type: Key;
          }
        : {
              type: Key;
              payload: M[Key];
          };
};
